### ISSUE TITLE
processing file failed because it does not have a .ps1 extension 

### ISSUE THREAD

**Issue by kenman731** [madbomb122/BlackViperScript#2]
Dear madbomb122,

I am having a problem running your script. I downloaded all of your files into a zip, then extracted them in my downloads folder: C:\Users\Kenny\Downloads\BlackViperScript-master  
When I right click the _Win10-BlackViper.bat file and run as admin i get this error: 

![unnamed](https://user-images.githubusercontent.com/29340318/27005449-77fc0caa-4de4-11e7-8712-2d49ef65dee4.png)

Please let me know how to fix this if possible. Thanks!

**Comment by madbomb122** [comment]
dunno why but your computer is detecting the script's path as "C:\Users\Kenny" the script's path instead of  "C:\Users\Kenny\Downloads\BlackViperScript-master\BlackViper-Win10.ps1" 

the only thing i could think of is
1. to move the script folder to another directory (Not in the path of "c:\users")
or 
2.  run the script directly and to use switches if you need to use any (see read me for switches)

**Comment by kenman731** [comment]
I got it to work! Thanks!

I ended up having to run the batch file from a flash drive
